export const ADD_STAFF = 'ADD_STAFF';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const STAFFS_RENDERING = 'STAFFS_RENDERING';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const SALARIES_LOADING = 'SALARIES_LOADING';